[project]
name = "pdf2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling[ocr]>=2.93.0",
    "google-generativeai>=0.8.6",
    "huggingface-hub>=0.36.2",
    "magic-pdf[full]>=0.6.1",
    "marker-pdf[full]>=1.10.2",
    "markitdown[all]>=0.1.5",
    "mlx-vlm>=0.3.9",
    "ocrmac>=1.0.1",
    "streamlit>=1.57.0",
    "streamlit-ace>=0.1.1",
]
